### ISSUE TITLE
Boolean Fragments

### ISSUE THREAD

**Issue by tryfon-mw** [nschloe/pygmsh#306]
hello,

I am having some issues with boolean fragments in 3d when using physical groups. It seems the primary physical group is "lost".
I am copying a test that fails when fragmenting a cube (physical 1) using a sphere (physical 2) where I would like to obtain the outer fragment as physical 1 and the inner fragment as physical 2.
I am having the same issue in 2d.

Thanks for the help

Tryfon
```python
def geo_cube(geo_object):
    """Construct square using built in geometry."""
    cube = geo_object.add_box([-0.5, -0.5, -0.5], [1, 1, 1], 0.1)
    return geo_object, cube

def geo_sphere(geo_object):
    """construct sphere"""
    sphere = geo_object.add_ball([0, 0, 0], 0.1)
    return geo_object, sphere

def test_fragments():
    """Test planar surface with holes.

    Construct it with boolean operations and verify that it is the same.
    """
    # construct surface using boolean
    geo_object = pygmsh.opencascade.Geometry(0.04, 0.04)
    geo_object, vol1 = geo_cube(geo_object)
    geo_object, vol2 = geo_sphere(geo_object)

    geo_object.add_physical([vol1], label=1)
    geo_object.add_physical([vol2], label=2)
    diff = geo_object.boolean_fragments([vol1], [vol2])
    mesh = pygmsh.generate_mesh(geo_object)
    assert np.abs((compute_volume(mesh) - 1) / 1) < 1e-3
    surf = 1 - 0.1 ** 3 * np.pi * 4 / 3
    outer_mask = np.where(mesh.cell_data["tetra"]["gmsh:physical"] == 1)[0]
    outer_cells = {}
    outer_cells["tetra"] = mesh.cells["tetra"][outer_mask]

    inner_mask = np.where(mesh.cell_data["tetra"]["gmsh:physical"] == 2)[0]
    inner_cells = {}
    inner_cells["tetra"] = mesh.cells["tetra"][inner_mask]

    value = compute_volume(meshio.Mesh(mesh.points, outer_cells))
    assert np.abs((value - surf)) < 1e-2 * surf
    return
```

**Comment by nschloe** [comment]
The code you posted does not run. Make sure I can just copy-and-paste it to see the error.

**Comment by tryfon-mw** [comment]
Indeed sorry. Here it goes:


"""Test module for boolean operations."""
import numpy as np

import meshio
import pygmsh
from helpers import compute_volume

def geo_cube(geo_object):
    """Construct square using built in geometry."""
    cube = geo_object.add_box([-0.5, -0.5, -0.5], [1, 1, 1], 0.1)
    return geo_object, cube

def geo_sphere(geo_object):
    """construct sphere"""
    sphere = geo_object.add_ball([0, 0, 0], 0.1)
    return geo_object, sphere

def test_fragments():
    """Test planar surface with holes.

    Construct it with boolean operations and verify that it is the same.
    """
    # construct surface using boolean
    geo_object = pygmsh.opencascade.Geometry(0.04, 0.04)
    geo_object, vol1 = geo_cube(geo_object)
    geo_object, vol2 = geo_sphere(geo_object)

    geo_object.add_physical([vol1], label=1)
    geo_object.add_physical([vol2], label=2)
    diff = geo_object.boolean_fragments([vol1], [vol2])
    mesh = pygmsh.generate_mesh(geo_object)
    assert np.abs((compute_volume(mesh) - 1) / 1) < 1e-3
    surf = 1 - 0.1 ** 3 * np.pi * 4 / 3
    outer_mask = np.where(mesh.cell_data["tetra"]["gmsh:physical"] == 1)[0]
    outer_cells = {}
    outer_cells["tetra"] = mesh.cells["tetra"][outer_mask]

    inner_mask = np.where(mesh.cell_data["tetra"]["gmsh:physical"] == 2)[0]
    inner_cells = {}
    inner_cells["tetra"] = mesh.cells["tetra"][inner_mask]

    value = compute_volume(meshio.Mesh(mesh.points, outer_cells))
    assert np.abs((value - surf)) < 1e-2 * surf
    return


if __name__ == "__main__":
    test_fragments()

**Comment by nschloe** [comment]
Best use triple back ticks to format your code. (You can edit your post, too.)

**Comment by nschloe** [comment]
Just ping me when you're done.

**Comment by tryfon-mw** [comment]
i think it should be ok now


Tryfon Antonakakis
Co Founder & CEO

Multiwave Technologies AG
3 Chemin du Pré Fleuri
1228, Geneva
Switzerland
+41 (0) 76 46 12 023
www.multiwave.ch

**Comment by tryfon-mw** [comment]
Just saw this, as it is maybe related:

http://onelab.info/pipermail/gmsh/2018/011896.html

**Comment by nschloe** [comment]
Still doesn't work.
```
Traceback (most recent call last):
  File "bb.py", line 6, in <module>
    from helpers import compute_volume
ModuleNotFoundError: No module named 'helpers'
```

**Comment by tryfon-mw** [comment]
Hi,

I updated the code and put helpers in there.

Let me know if that is ok

Thanks

Tryfon

Tryfon Antonakakis
Co Founder & CEO

Multiwave Technologies AG
3 Chemin du Pré Fleuri
1228, Geneva
Switzerland
+41 (0) 76 46 12 023
www.multiwave.ch

**Comment by nschloe** [comment]
I still cannot run this code. `get_simplex_volumes` is undefined. Also you're using and old version of meshio. Apparently you have not tried to run the code yourself, for the third time, but expect me to do it. I don't think that is very nice.

Please update your code accordingly. Also make sure to keep it _minimal_. I will close this PR. Feel free to reopen with a running code.

**Comment by tryfon-mw** [comment]
Of course i ran the code on my system. 
The code runs fine on my system so it s not easy find what is wrong.

Anyway i ll revert back

tryfon

**Comment by tryfon-mw** [comment]
The test in test_booleans.py 
test_fragments_with_physical() is the one that describes the issue.
